# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fmcore', [dirname(__file__)])
        except ImportError:
            import _fmcore
            return _fmcore
        if fp is not None:
            try:
                _mod = imp.load_module('_fmcore', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _fmcore = swig_import_helper()
    del swig_import_helper
else:
    import _fmcore
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


FM_OK = _fmcore.FM_OK
FM_ERROR = _fmcore.FM_ERROR

def fmLogConstructName(*args):
  return _fmcore.fmLogConstructName(*args)
fmLogConstructName = _fmcore.fmLogConstructName

def fmLogInit(*args):
  return _fmcore.fmLogInit(*args)
fmLogInit = _fmcore.fmLogInit

def fmLogWrite(*args):
  return _fmcore.fmLogWrite(*args)
fmLogWrite = _fmcore.fmLogWrite

def fmLogFlush():
  return _fmcore.fmLogFlush()
fmLogFlush = _fmcore.fmLogFlush

def fmLogClose():
  return _fmcore.fmLogClose()
fmLogClose = _fmcore.fmLogClose

def fmMsgLogInit(*args):
  return _fmcore.fmMsgLogInit(*args)
fmMsgLogInit = _fmcore.fmMsgLogInit

def fmMsgLogWrite(*args):
  return _fmcore.fmMsgLogWrite(*args)
fmMsgLogWrite = _fmcore.fmMsgLogWrite

def fmMsgLogFlush():
  return _fmcore.fmMsgLogFlush()
fmMsgLogFlush = _fmcore.fmMsgLogFlush

def fmMsgLogClose():
  return _fmcore.fmMsgLogClose()
fmMsgLogClose = _fmcore.fmMsgLogClose
FMMESSAGE_TOTALMSIZE = _fmcore.FMMESSAGE_TOTALMSIZE
FMMESSAGE_MCOUNT = _fmcore.FMMESSAGE_MCOUNT
FMMESSAGE_BUFSIZE = _fmcore.FMMESSAGE_BUFSIZE
DUMMY_ID = _fmcore.DUMMY_ID
FMSTATE_ID = _fmcore.FMSTATE_ID
FMOPTITRACK_ID = _fmcore.FMOPTITRACK_ID
FMSENSOR_ID = _fmcore.FMSENSOR_ID
FMRAWSENSOR_ID = _fmcore.FMRAWSENSOR_ID
FMROTOR_ID = _fmcore.FMROTOR_ID
FMMOTORINPUT_ID = _fmcore.FMMOTORINPUT_ID
FMCONTROL_ID = _fmcore.FMCONTROL_ID
FMSTATE2_ID = _fmcore.FMSTATE2_ID
FMOPTITRACK2_ID = _fmcore.FMOPTITRACK2_ID
FMSTATUS_ID = _fmcore.FMSTATUS_ID
FMINNERLOOP_ID = _fmcore.FMINNERLOOP_ID
FMMESSAGE_COUNT = _fmcore.FMMESSAGE_COUNT
FMCMD_RESET = _fmcore.FMCMD_RESET
FMCMD_RESETAIRCRAFT = _fmcore.FMCMD_RESETAIRCRAFT
FMCMD_RESETAIRCRAFTDONE = _fmcore.FMCMD_RESETAIRCRAFTDONE
FMCMD_PATHSYMBOLREQUEST = _fmcore.FMCMD_PATHSYMBOLREQUEST
FMCMD_STARTINTERFACE = _fmcore.FMCMD_STARTINTERFACE
FMCMD_STARTTRIAL = _fmcore.FMCMD_STARTTRIAL
FMCMD_STOPTRIAL = _fmcore.FMCMD_STOPTRIAL
FMCMD_GOHOME = _fmcore.FMCMD_GOHOME
FMCMD_FAILSAFE = _fmcore.FMCMD_FAILSAFE
FMCMD_HEARTBEAT = _fmcore.FMCMD_HEARTBEAT
FMCMD_STARTSIMULATION = _fmcore.FMCMD_STARTSIMULATION
FMCMD_STARTSIMULATION2 = _fmcore.FMCMD_STARTSIMULATION2
FMCMD_TOGGLECAMERAPITCH = _fmcore.FMCMD_TOGGLECAMERAPITCH
FMCMD_TOGGLECAMERAROLL = _fmcore.FMCMD_TOGGLECAMERAROLL
FMSTAT_AP = _fmcore.FMSTAT_AP
FMSTAT_GUMSTIX = _fmcore.FMSTAT_GUMSTIX
class TFmMessage(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmMessage, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmMessage, name)
    __repr__ = _swig_repr
    __swig_setmethods__["iMsgId"] = _fmcore.TFmMessage_iMsgId_set
    __swig_getmethods__["iMsgId"] = _fmcore.TFmMessage_iMsgId_get
    if _newclass:iMsgId = _swig_property(_fmcore.TFmMessage_iMsgId_get, _fmcore.TFmMessage_iMsgId_set)
    __swig_setmethods__["iMsgSize"] = _fmcore.TFmMessage_iMsgSize_set
    __swig_getmethods__["iMsgSize"] = _fmcore.TFmMessage_iMsgSize_get
    if _newclass:iMsgSize = _swig_property(_fmcore.TFmMessage_iMsgSize_get, _fmcore.TFmMessage_iMsgSize_set)
    __swig_setmethods__["data"] = _fmcore.TFmMessage_data_set
    __swig_getmethods__["data"] = _fmcore.TFmMessage_data_get
    if _newclass:data = _swig_property(_fmcore.TFmMessage_data_get, _fmcore.TFmMessage_data_set)
    def __init__(self): 
        this = _fmcore.new_TFmMessage()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmMessage
    __del__ = lambda self : None;
TFmMessage_swigregister = _fmcore.TFmMessage_swigregister
TFmMessage_swigregister(TFmMessage)

class TFmQueue(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmQueue, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmQueue, name)
    __repr__ = _swig_repr
    __swig_setmethods__["buf"] = _fmcore.TFmQueue_buf_set
    __swig_getmethods__["buf"] = _fmcore.TFmQueue_buf_get
    if _newclass:buf = _swig_property(_fmcore.TFmQueue_buf_get, _fmcore.TFmQueue_buf_set)
    __swig_setmethods__["bufPos"] = _fmcore.TFmQueue_bufPos_set
    __swig_getmethods__["bufPos"] = _fmcore.TFmQueue_bufPos_get
    if _newclass:bufPos = _swig_property(_fmcore.TFmQueue_bufPos_get, _fmcore.TFmQueue_bufPos_set)
    __swig_setmethods__["msgHead"] = _fmcore.TFmQueue_msgHead_set
    __swig_getmethods__["msgHead"] = _fmcore.TFmQueue_msgHead_get
    if _newclass:msgHead = _swig_property(_fmcore.TFmQueue_msgHead_get, _fmcore.TFmQueue_msgHead_set)
    __swig_setmethods__["msgTail"] = _fmcore.TFmQueue_msgTail_set
    __swig_getmethods__["msgTail"] = _fmcore.TFmQueue_msgTail_get
    if _newclass:msgTail = _swig_property(_fmcore.TFmQueue_msgTail_get, _fmcore.TFmQueue_msgTail_set)
    __swig_setmethods__["msg"] = _fmcore.TFmQueue_msg_set
    __swig_getmethods__["msg"] = _fmcore.TFmQueue_msg_get
    if _newclass:msg = _swig_property(_fmcore.TFmQueue_msg_get, _fmcore.TFmQueue_msg_set)
    def __init__(self): 
        this = _fmcore.new_TFmQueue()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmQueue
    __del__ = lambda self : None;
TFmQueue_swigregister = _fmcore.TFmQueue_swigregister
TFmQueue_swigregister(TFmQueue)

class TFmDataString(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmDataString, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmDataString, name)
    __repr__ = _swig_repr
    __swig_setmethods__["size"] = _fmcore.TFmDataString_size_set
    __swig_getmethods__["size"] = _fmcore.TFmDataString_size_get
    if _newclass:size = _swig_property(_fmcore.TFmDataString_size_get, _fmcore.TFmDataString_size_set)
    __swig_setmethods__["data"] = _fmcore.TFmDataString_data_set
    __swig_getmethods__["data"] = _fmcore.TFmDataString_data_get
    if _newclass:data = _swig_property(_fmcore.TFmDataString_data_get, _fmcore.TFmDataString_data_set)
    def __init__(self): 
        this = _fmcore.new_TFmDataString()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmDataString
    __del__ = lambda self : None;
TFmDataString_swigregister = _fmcore.TFmDataString_swigregister
TFmDataString_swigregister(TFmDataString)


def fmInitMessage():
  return _fmcore.fmInitMessage()
fmInitMessage = _fmcore.fmInitMessage

def fmInitMessageQ(*args):
  return _fmcore.fmInitMessageQ(*args)
fmInitMessageQ = _fmcore.fmInitMessageQ

def fmFreeMessage(*args):
  return _fmcore.fmFreeMessage(*args)
fmFreeMessage = _fmcore.fmFreeMessage

def fmDataString(*args):
  return _fmcore.fmDataString(*args)
fmDataString = _fmcore.fmDataString

def fmMessageFromBuffer(*args):
  return _fmcore.fmMessageFromBuffer(*args)
fmMessageFromBuffer = _fmcore.fmMessageFromBuffer

def fmReceiveData(*args):
  return _fmcore.fmReceiveData(*args)
fmReceiveData = _fmcore.fmReceiveData

def fmReceiveDataQ(*args):
  return _fmcore.fmReceiveDataQ(*args)
fmReceiveDataQ = _fmcore.fmReceiveDataQ

def fmPopMessage():
  return _fmcore.fmPopMessage()
fmPopMessage = _fmcore.fmPopMessage

def fmPopMessageQ(*args):
  return _fmcore.fmPopMessageQ(*args)
fmPopMessageQ = _fmcore.fmPopMessageQ

def fmPlaceMessageQ(*args):
  return _fmcore.fmPlaceMessageQ(*args)
fmPlaceMessageQ = _fmcore.fmPlaceMessageQ
class TFmStateObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmStateObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmStateObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dT"] = _fmcore.TFmStateObject_dT_set
    __swig_getmethods__["dT"] = _fmcore.TFmStateObject_dT_get
    if _newclass:dT = _swig_property(_fmcore.TFmStateObject_dT_get, _fmcore.TFmStateObject_dT_set)
    __swig_setmethods__["dX"] = _fmcore.TFmStateObject_dX_set
    __swig_getmethods__["dX"] = _fmcore.TFmStateObject_dX_get
    if _newclass:dX = _swig_property(_fmcore.TFmStateObject_dX_get, _fmcore.TFmStateObject_dX_set)
    __swig_setmethods__["dY"] = _fmcore.TFmStateObject_dY_set
    __swig_getmethods__["dY"] = _fmcore.TFmStateObject_dY_get
    if _newclass:dY = _swig_property(_fmcore.TFmStateObject_dY_get, _fmcore.TFmStateObject_dY_set)
    __swig_setmethods__["dZ"] = _fmcore.TFmStateObject_dZ_set
    __swig_getmethods__["dZ"] = _fmcore.TFmStateObject_dZ_get
    if _newclass:dZ = _swig_property(_fmcore.TFmStateObject_dZ_get, _fmcore.TFmStateObject_dZ_set)
    __swig_setmethods__["dVx"] = _fmcore.TFmStateObject_dVx_set
    __swig_getmethods__["dVx"] = _fmcore.TFmStateObject_dVx_get
    if _newclass:dVx = _swig_property(_fmcore.TFmStateObject_dVx_get, _fmcore.TFmStateObject_dVx_set)
    __swig_setmethods__["dVy"] = _fmcore.TFmStateObject_dVy_set
    __swig_getmethods__["dVy"] = _fmcore.TFmStateObject_dVy_get
    if _newclass:dVy = _swig_property(_fmcore.TFmStateObject_dVy_get, _fmcore.TFmStateObject_dVy_set)
    __swig_setmethods__["dVz"] = _fmcore.TFmStateObject_dVz_set
    __swig_getmethods__["dVz"] = _fmcore.TFmStateObject_dVz_get
    if _newclass:dVz = _swig_property(_fmcore.TFmStateObject_dVz_get, _fmcore.TFmStateObject_dVz_set)
    __swig_setmethods__["dPhi"] = _fmcore.TFmStateObject_dPhi_set
    __swig_getmethods__["dPhi"] = _fmcore.TFmStateObject_dPhi_get
    if _newclass:dPhi = _swig_property(_fmcore.TFmStateObject_dPhi_get, _fmcore.TFmStateObject_dPhi_set)
    __swig_setmethods__["dTheta"] = _fmcore.TFmStateObject_dTheta_set
    __swig_getmethods__["dTheta"] = _fmcore.TFmStateObject_dTheta_get
    if _newclass:dTheta = _swig_property(_fmcore.TFmStateObject_dTheta_get, _fmcore.TFmStateObject_dTheta_set)
    __swig_setmethods__["dPsi"] = _fmcore.TFmStateObject_dPsi_set
    __swig_getmethods__["dPsi"] = _fmcore.TFmStateObject_dPsi_get
    if _newclass:dPsi = _swig_property(_fmcore.TFmStateObject_dPsi_get, _fmcore.TFmStateObject_dPsi_set)
    __swig_setmethods__["dP"] = _fmcore.TFmStateObject_dP_set
    __swig_getmethods__["dP"] = _fmcore.TFmStateObject_dP_get
    if _newclass:dP = _swig_property(_fmcore.TFmStateObject_dP_get, _fmcore.TFmStateObject_dP_set)
    __swig_setmethods__["dQ"] = _fmcore.TFmStateObject_dQ_set
    __swig_getmethods__["dQ"] = _fmcore.TFmStateObject_dQ_get
    if _newclass:dQ = _swig_property(_fmcore.TFmStateObject_dQ_get, _fmcore.TFmStateObject_dQ_set)
    __swig_setmethods__["dR"] = _fmcore.TFmStateObject_dR_set
    __swig_getmethods__["dR"] = _fmcore.TFmStateObject_dR_get
    if _newclass:dR = _swig_property(_fmcore.TFmStateObject_dR_get, _fmcore.TFmStateObject_dR_set)
    def __init__(self): 
        this = _fmcore.new_TFmStateObject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmStateObject
    __del__ = lambda self : None;
TFmStateObject_swigregister = _fmcore.TFmStateObject_swigregister
TFmStateObject_swigregister(TFmStateObject)


def fmStateObject_serialize(*args):
  return _fmcore.fmStateObject_serialize(*args)
fmStateObject_serialize = _fmcore.fmStateObject_serialize

def fmStateObject_deserialize(*args):
  return _fmcore.fmStateObject_deserialize(*args)
fmStateObject_deserialize = _fmcore.fmStateObject_deserialize

def fmStateObject_tomessage(*args):
  return _fmcore.fmStateObject_tomessage(*args)
fmStateObject_tomessage = _fmcore.fmStateObject_tomessage

def fmStateObject_frommessage(*args):
  return _fmcore.fmStateObject_frommessage(*args)
fmStateObject_frommessage = _fmcore.fmStateObject_frommessage
class TFmSensorObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmSensorObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmSensorObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dT"] = _fmcore.TFmSensorObject_dT_set
    __swig_getmethods__["dT"] = _fmcore.TFmSensorObject_dT_get
    if _newclass:dT = _swig_property(_fmcore.TFmSensorObject_dT_get, _fmcore.TFmSensorObject_dT_set)
    __swig_setmethods__["dPhi"] = _fmcore.TFmSensorObject_dPhi_set
    __swig_getmethods__["dPhi"] = _fmcore.TFmSensorObject_dPhi_get
    if _newclass:dPhi = _swig_property(_fmcore.TFmSensorObject_dPhi_get, _fmcore.TFmSensorObject_dPhi_set)
    __swig_setmethods__["dTheta"] = _fmcore.TFmSensorObject_dTheta_set
    __swig_getmethods__["dTheta"] = _fmcore.TFmSensorObject_dTheta_get
    if _newclass:dTheta = _swig_property(_fmcore.TFmSensorObject_dTheta_get, _fmcore.TFmSensorObject_dTheta_set)
    __swig_setmethods__["dPsi"] = _fmcore.TFmSensorObject_dPsi_set
    __swig_getmethods__["dPsi"] = _fmcore.TFmSensorObject_dPsi_get
    if _newclass:dPsi = _swig_property(_fmcore.TFmSensorObject_dPsi_get, _fmcore.TFmSensorObject_dPsi_set)
    __swig_setmethods__["dVx"] = _fmcore.TFmSensorObject_dVx_set
    __swig_getmethods__["dVx"] = _fmcore.TFmSensorObject_dVx_get
    if _newclass:dVx = _swig_property(_fmcore.TFmSensorObject_dVx_get, _fmcore.TFmSensorObject_dVx_set)
    __swig_setmethods__["dVy"] = _fmcore.TFmSensorObject_dVy_set
    __swig_getmethods__["dVy"] = _fmcore.TFmSensorObject_dVy_get
    if _newclass:dVy = _swig_property(_fmcore.TFmSensorObject_dVy_get, _fmcore.TFmSensorObject_dVy_set)
    __swig_setmethods__["dVz"] = _fmcore.TFmSensorObject_dVz_set
    __swig_getmethods__["dVz"] = _fmcore.TFmSensorObject_dVz_get
    if _newclass:dVz = _swig_property(_fmcore.TFmSensorObject_dVz_get, _fmcore.TFmSensorObject_dVz_set)
    __swig_setmethods__["dP"] = _fmcore.TFmSensorObject_dP_set
    __swig_getmethods__["dP"] = _fmcore.TFmSensorObject_dP_get
    if _newclass:dP = _swig_property(_fmcore.TFmSensorObject_dP_get, _fmcore.TFmSensorObject_dP_set)
    __swig_setmethods__["dQ"] = _fmcore.TFmSensorObject_dQ_set
    __swig_getmethods__["dQ"] = _fmcore.TFmSensorObject_dQ_get
    if _newclass:dQ = _swig_property(_fmcore.TFmSensorObject_dQ_get, _fmcore.TFmSensorObject_dQ_set)
    __swig_setmethods__["dR"] = _fmcore.TFmSensorObject_dR_set
    __swig_getmethods__["dR"] = _fmcore.TFmSensorObject_dR_get
    if _newclass:dR = _swig_property(_fmcore.TFmSensorObject_dR_get, _fmcore.TFmSensorObject_dR_set)
    __swig_setmethods__["dAx"] = _fmcore.TFmSensorObject_dAx_set
    __swig_getmethods__["dAx"] = _fmcore.TFmSensorObject_dAx_get
    if _newclass:dAx = _swig_property(_fmcore.TFmSensorObject_dAx_get, _fmcore.TFmSensorObject_dAx_set)
    __swig_setmethods__["dAy"] = _fmcore.TFmSensorObject_dAy_set
    __swig_getmethods__["dAy"] = _fmcore.TFmSensorObject_dAy_get
    if _newclass:dAy = _swig_property(_fmcore.TFmSensorObject_dAy_get, _fmcore.TFmSensorObject_dAy_set)
    __swig_setmethods__["dAz"] = _fmcore.TFmSensorObject_dAz_set
    __swig_getmethods__["dAz"] = _fmcore.TFmSensorObject_dAz_get
    if _newclass:dAz = _swig_property(_fmcore.TFmSensorObject_dAz_get, _fmcore.TFmSensorObject_dAz_set)
    __swig_setmethods__["dHx"] = _fmcore.TFmSensorObject_dHx_set
    __swig_getmethods__["dHx"] = _fmcore.TFmSensorObject_dHx_get
    if _newclass:dHx = _swig_property(_fmcore.TFmSensorObject_dHx_get, _fmcore.TFmSensorObject_dHx_set)
    __swig_setmethods__["dHy"] = _fmcore.TFmSensorObject_dHy_set
    __swig_getmethods__["dHy"] = _fmcore.TFmSensorObject_dHy_get
    if _newclass:dHy = _swig_property(_fmcore.TFmSensorObject_dHy_get, _fmcore.TFmSensorObject_dHy_set)
    __swig_setmethods__["dHz"] = _fmcore.TFmSensorObject_dHz_set
    __swig_getmethods__["dHz"] = _fmcore.TFmSensorObject_dHz_get
    if _newclass:dHz = _swig_property(_fmcore.TFmSensorObject_dHz_get, _fmcore.TFmSensorObject_dHz_set)
    __swig_setmethods__["dPressure"] = _fmcore.TFmSensorObject_dPressure_set
    __swig_getmethods__["dPressure"] = _fmcore.TFmSensorObject_dPressure_get
    if _newclass:dPressure = _swig_property(_fmcore.TFmSensorObject_dPressure_get, _fmcore.TFmSensorObject_dPressure_set)
    def __init__(self): 
        this = _fmcore.new_TFmSensorObject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmSensorObject
    __del__ = lambda self : None;
TFmSensorObject_swigregister = _fmcore.TFmSensorObject_swigregister
TFmSensorObject_swigregister(TFmSensorObject)


def fmSensorObject_serialize(*args):
  return _fmcore.fmSensorObject_serialize(*args)
fmSensorObject_serialize = _fmcore.fmSensorObject_serialize

def fmSensorObject_deserialize(*args):
  return _fmcore.fmSensorObject_deserialize(*args)
fmSensorObject_deserialize = _fmcore.fmSensorObject_deserialize

def fmSensorObject_tomessage(*args):
  return _fmcore.fmSensorObject_tomessage(*args)
fmSensorObject_tomessage = _fmcore.fmSensorObject_tomessage

def fmSensorObject_frommessage(*args):
  return _fmcore.fmSensorObject_frommessage(*args)
fmSensorObject_frommessage = _fmcore.fmSensorObject_frommessage
class TFmRawSensorObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmRawSensorObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmRawSensorObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dT"] = _fmcore.TFmRawSensorObject_dT_set
    __swig_getmethods__["dT"] = _fmcore.TFmRawSensorObject_dT_get
    if _newclass:dT = _swig_property(_fmcore.TFmRawSensorObject_dT_get, _fmcore.TFmRawSensorObject_dT_set)
    __swig_setmethods__["dP"] = _fmcore.TFmRawSensorObject_dP_set
    __swig_getmethods__["dP"] = _fmcore.TFmRawSensorObject_dP_get
    if _newclass:dP = _swig_property(_fmcore.TFmRawSensorObject_dP_get, _fmcore.TFmRawSensorObject_dP_set)
    __swig_setmethods__["dQ"] = _fmcore.TFmRawSensorObject_dQ_set
    __swig_getmethods__["dQ"] = _fmcore.TFmRawSensorObject_dQ_get
    if _newclass:dQ = _swig_property(_fmcore.TFmRawSensorObject_dQ_get, _fmcore.TFmRawSensorObject_dQ_set)
    __swig_setmethods__["dR"] = _fmcore.TFmRawSensorObject_dR_set
    __swig_getmethods__["dR"] = _fmcore.TFmRawSensorObject_dR_get
    if _newclass:dR = _swig_property(_fmcore.TFmRawSensorObject_dR_get, _fmcore.TFmRawSensorObject_dR_set)
    __swig_setmethods__["dAx"] = _fmcore.TFmRawSensorObject_dAx_set
    __swig_getmethods__["dAx"] = _fmcore.TFmRawSensorObject_dAx_get
    if _newclass:dAx = _swig_property(_fmcore.TFmRawSensorObject_dAx_get, _fmcore.TFmRawSensorObject_dAx_set)
    __swig_setmethods__["dAy"] = _fmcore.TFmRawSensorObject_dAy_set
    __swig_getmethods__["dAy"] = _fmcore.TFmRawSensorObject_dAy_get
    if _newclass:dAy = _swig_property(_fmcore.TFmRawSensorObject_dAy_get, _fmcore.TFmRawSensorObject_dAy_set)
    __swig_setmethods__["dAz"] = _fmcore.TFmRawSensorObject_dAz_set
    __swig_getmethods__["dAz"] = _fmcore.TFmRawSensorObject_dAz_get
    if _newclass:dAz = _swig_property(_fmcore.TFmRawSensorObject_dAz_get, _fmcore.TFmRawSensorObject_dAz_set)
    __swig_setmethods__["dMagx"] = _fmcore.TFmRawSensorObject_dMagx_set
    __swig_getmethods__["dMagx"] = _fmcore.TFmRawSensorObject_dMagx_get
    if _newclass:dMagx = _swig_property(_fmcore.TFmRawSensorObject_dMagx_get, _fmcore.TFmRawSensorObject_dMagx_set)
    __swig_setmethods__["dMagy"] = _fmcore.TFmRawSensorObject_dMagy_set
    __swig_getmethods__["dMagy"] = _fmcore.TFmRawSensorObject_dMagy_get
    if _newclass:dMagy = _swig_property(_fmcore.TFmRawSensorObject_dMagy_get, _fmcore.TFmRawSensorObject_dMagy_set)
    __swig_setmethods__["dMagz"] = _fmcore.TFmRawSensorObject_dMagz_set
    __swig_getmethods__["dMagz"] = _fmcore.TFmRawSensorObject_dMagz_get
    if _newclass:dMagz = _swig_property(_fmcore.TFmRawSensorObject_dMagz_get, _fmcore.TFmRawSensorObject_dMagz_set)
    __swig_setmethods__["dPressure"] = _fmcore.TFmRawSensorObject_dPressure_set
    __swig_getmethods__["dPressure"] = _fmcore.TFmRawSensorObject_dPressure_get
    if _newclass:dPressure = _swig_property(_fmcore.TFmRawSensorObject_dPressure_get, _fmcore.TFmRawSensorObject_dPressure_set)
    def __init__(self): 
        this = _fmcore.new_TFmRawSensorObject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmRawSensorObject
    __del__ = lambda self : None;
TFmRawSensorObject_swigregister = _fmcore.TFmRawSensorObject_swigregister
TFmRawSensorObject_swigregister(TFmRawSensorObject)


def fmRawSensorObject_serialize(*args):
  return _fmcore.fmRawSensorObject_serialize(*args)
fmRawSensorObject_serialize = _fmcore.fmRawSensorObject_serialize

def fmRawSensorObject_deserialize(*args):
  return _fmcore.fmRawSensorObject_deserialize(*args)
fmRawSensorObject_deserialize = _fmcore.fmRawSensorObject_deserialize

def fmRawSensorObject_tomessage(*args):
  return _fmcore.fmRawSensorObject_tomessage(*args)
fmRawSensorObject_tomessage = _fmcore.fmRawSensorObject_tomessage

def fmRawSensorObject_frommessage(*args):
  return _fmcore.fmRawSensorObject_frommessage(*args)
fmRawSensorObject_frommessage = _fmcore.fmRawSensorObject_frommessage
class TFmOptitrackObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmOptitrackObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmOptitrackObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["iFrame"] = _fmcore.TFmOptitrackObject_iFrame_set
    __swig_getmethods__["iFrame"] = _fmcore.TFmOptitrackObject_iFrame_get
    if _newclass:iFrame = _swig_property(_fmcore.TFmOptitrackObject_iFrame_get, _fmcore.TFmOptitrackObject_iFrame_set)
    __swig_setmethods__["dT"] = _fmcore.TFmOptitrackObject_dT_set
    __swig_getmethods__["dT"] = _fmcore.TFmOptitrackObject_dT_get
    if _newclass:dT = _swig_property(_fmcore.TFmOptitrackObject_dT_get, _fmcore.TFmOptitrackObject_dT_set)
    __swig_setmethods__["dX"] = _fmcore.TFmOptitrackObject_dX_set
    __swig_getmethods__["dX"] = _fmcore.TFmOptitrackObject_dX_get
    if _newclass:dX = _swig_property(_fmcore.TFmOptitrackObject_dX_get, _fmcore.TFmOptitrackObject_dX_set)
    __swig_setmethods__["dY"] = _fmcore.TFmOptitrackObject_dY_set
    __swig_getmethods__["dY"] = _fmcore.TFmOptitrackObject_dY_get
    if _newclass:dY = _swig_property(_fmcore.TFmOptitrackObject_dY_get, _fmcore.TFmOptitrackObject_dY_set)
    __swig_setmethods__["dZ"] = _fmcore.TFmOptitrackObject_dZ_set
    __swig_getmethods__["dZ"] = _fmcore.TFmOptitrackObject_dZ_get
    if _newclass:dZ = _swig_property(_fmcore.TFmOptitrackObject_dZ_get, _fmcore.TFmOptitrackObject_dZ_set)
    __swig_setmethods__["dPhi"] = _fmcore.TFmOptitrackObject_dPhi_set
    __swig_getmethods__["dPhi"] = _fmcore.TFmOptitrackObject_dPhi_get
    if _newclass:dPhi = _swig_property(_fmcore.TFmOptitrackObject_dPhi_get, _fmcore.TFmOptitrackObject_dPhi_set)
    __swig_setmethods__["dTheta"] = _fmcore.TFmOptitrackObject_dTheta_set
    __swig_getmethods__["dTheta"] = _fmcore.TFmOptitrackObject_dTheta_get
    if _newclass:dTheta = _swig_property(_fmcore.TFmOptitrackObject_dTheta_get, _fmcore.TFmOptitrackObject_dTheta_set)
    __swig_setmethods__["dPsi"] = _fmcore.TFmOptitrackObject_dPsi_set
    __swig_getmethods__["dPsi"] = _fmcore.TFmOptitrackObject_dPsi_get
    if _newclass:dPsi = _swig_property(_fmcore.TFmOptitrackObject_dPsi_get, _fmcore.TFmOptitrackObject_dPsi_set)
    def __init__(self): 
        this = _fmcore.new_TFmOptitrackObject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmOptitrackObject
    __del__ = lambda self : None;
TFmOptitrackObject_swigregister = _fmcore.TFmOptitrackObject_swigregister
TFmOptitrackObject_swigregister(TFmOptitrackObject)


def fmOptitrackObject_serialize(*args):
  return _fmcore.fmOptitrackObject_serialize(*args)
fmOptitrackObject_serialize = _fmcore.fmOptitrackObject_serialize

def fmOptitrackObject_deserialize(*args):
  return _fmcore.fmOptitrackObject_deserialize(*args)
fmOptitrackObject_deserialize = _fmcore.fmOptitrackObject_deserialize

def fmOptitrackObject_tomessage(*args):
  return _fmcore.fmOptitrackObject_tomessage(*args)
fmOptitrackObject_tomessage = _fmcore.fmOptitrackObject_tomessage

def fmOptitrackObject_frommessage(*args):
  return _fmcore.fmOptitrackObject_frommessage(*args)
fmOptitrackObject_frommessage = _fmcore.fmOptitrackObject_frommessage
class TFmOptitrackObject2(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmOptitrackObject2, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmOptitrackObject2, name)
    __repr__ = _swig_repr
    __swig_setmethods__["iFrame"] = _fmcore.TFmOptitrackObject2_iFrame_set
    __swig_getmethods__["iFrame"] = _fmcore.TFmOptitrackObject2_iFrame_get
    if _newclass:iFrame = _swig_property(_fmcore.TFmOptitrackObject2_iFrame_get, _fmcore.TFmOptitrackObject2_iFrame_set)
    __swig_setmethods__["dT"] = _fmcore.TFmOptitrackObject2_dT_set
    __swig_getmethods__["dT"] = _fmcore.TFmOptitrackObject2_dT_get
    if _newclass:dT = _swig_property(_fmcore.TFmOptitrackObject2_dT_get, _fmcore.TFmOptitrackObject2_dT_set)
    __swig_setmethods__["dX"] = _fmcore.TFmOptitrackObject2_dX_set
    __swig_getmethods__["dX"] = _fmcore.TFmOptitrackObject2_dX_get
    if _newclass:dX = _swig_property(_fmcore.TFmOptitrackObject2_dX_get, _fmcore.TFmOptitrackObject2_dX_set)
    __swig_setmethods__["dY"] = _fmcore.TFmOptitrackObject2_dY_set
    __swig_getmethods__["dY"] = _fmcore.TFmOptitrackObject2_dY_get
    if _newclass:dY = _swig_property(_fmcore.TFmOptitrackObject2_dY_get, _fmcore.TFmOptitrackObject2_dY_set)
    __swig_setmethods__["dZ"] = _fmcore.TFmOptitrackObject2_dZ_set
    __swig_getmethods__["dZ"] = _fmcore.TFmOptitrackObject2_dZ_get
    if _newclass:dZ = _swig_property(_fmcore.TFmOptitrackObject2_dZ_get, _fmcore.TFmOptitrackObject2_dZ_set)
    __swig_setmethods__["dVx"] = _fmcore.TFmOptitrackObject2_dVx_set
    __swig_getmethods__["dVx"] = _fmcore.TFmOptitrackObject2_dVx_get
    if _newclass:dVx = _swig_property(_fmcore.TFmOptitrackObject2_dVx_get, _fmcore.TFmOptitrackObject2_dVx_set)
    __swig_setmethods__["dVy"] = _fmcore.TFmOptitrackObject2_dVy_set
    __swig_getmethods__["dVy"] = _fmcore.TFmOptitrackObject2_dVy_get
    if _newclass:dVy = _swig_property(_fmcore.TFmOptitrackObject2_dVy_get, _fmcore.TFmOptitrackObject2_dVy_set)
    __swig_setmethods__["dVz"] = _fmcore.TFmOptitrackObject2_dVz_set
    __swig_getmethods__["dVz"] = _fmcore.TFmOptitrackObject2_dVz_get
    if _newclass:dVz = _swig_property(_fmcore.TFmOptitrackObject2_dVz_get, _fmcore.TFmOptitrackObject2_dVz_set)
    __swig_setmethods__["dPhi"] = _fmcore.TFmOptitrackObject2_dPhi_set
    __swig_getmethods__["dPhi"] = _fmcore.TFmOptitrackObject2_dPhi_get
    if _newclass:dPhi = _swig_property(_fmcore.TFmOptitrackObject2_dPhi_get, _fmcore.TFmOptitrackObject2_dPhi_set)
    __swig_setmethods__["dTheta"] = _fmcore.TFmOptitrackObject2_dTheta_set
    __swig_getmethods__["dTheta"] = _fmcore.TFmOptitrackObject2_dTheta_get
    if _newclass:dTheta = _swig_property(_fmcore.TFmOptitrackObject2_dTheta_get, _fmcore.TFmOptitrackObject2_dTheta_set)
    __swig_setmethods__["dPsi"] = _fmcore.TFmOptitrackObject2_dPsi_set
    __swig_getmethods__["dPsi"] = _fmcore.TFmOptitrackObject2_dPsi_get
    if _newclass:dPsi = _swig_property(_fmcore.TFmOptitrackObject2_dPsi_get, _fmcore.TFmOptitrackObject2_dPsi_set)
    __swig_setmethods__["dP"] = _fmcore.TFmOptitrackObject2_dP_set
    __swig_getmethods__["dP"] = _fmcore.TFmOptitrackObject2_dP_get
    if _newclass:dP = _swig_property(_fmcore.TFmOptitrackObject2_dP_get, _fmcore.TFmOptitrackObject2_dP_set)
    __swig_setmethods__["dQ"] = _fmcore.TFmOptitrackObject2_dQ_set
    __swig_getmethods__["dQ"] = _fmcore.TFmOptitrackObject2_dQ_get
    if _newclass:dQ = _swig_property(_fmcore.TFmOptitrackObject2_dQ_get, _fmcore.TFmOptitrackObject2_dQ_set)
    __swig_setmethods__["dR"] = _fmcore.TFmOptitrackObject2_dR_set
    __swig_getmethods__["dR"] = _fmcore.TFmOptitrackObject2_dR_get
    if _newclass:dR = _swig_property(_fmcore.TFmOptitrackObject2_dR_get, _fmcore.TFmOptitrackObject2_dR_set)
    def __init__(self): 
        this = _fmcore.new_TFmOptitrackObject2()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmOptitrackObject2
    __del__ = lambda self : None;
TFmOptitrackObject2_swigregister = _fmcore.TFmOptitrackObject2_swigregister
TFmOptitrackObject2_swigregister(TFmOptitrackObject2)


def fmOptitrackObject2_serialize(*args):
  return _fmcore.fmOptitrackObject2_serialize(*args)
fmOptitrackObject2_serialize = _fmcore.fmOptitrackObject2_serialize

def fmOptitrackObject2_deserialize(*args):
  return _fmcore.fmOptitrackObject2_deserialize(*args)
fmOptitrackObject2_deserialize = _fmcore.fmOptitrackObject2_deserialize

def fmOptitrackObject2_tomessage(*args):
  return _fmcore.fmOptitrackObject2_tomessage(*args)
fmOptitrackObject2_tomessage = _fmcore.fmOptitrackObject2_tomessage

def fmOptitrackObject2_frommessage(*args):
  return _fmcore.fmOptitrackObject2_frommessage(*args)
fmOptitrackObject2_frommessage = _fmcore.fmOptitrackObject2_frommessage
class TFmMotorInputObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmMotorInputObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmMotorInputObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dT"] = _fmcore.TFmMotorInputObject_dT_set
    __swig_getmethods__["dT"] = _fmcore.TFmMotorInputObject_dT_get
    if _newclass:dT = _swig_property(_fmcore.TFmMotorInputObject_dT_get, _fmcore.TFmMotorInputObject_dT_set)
    __swig_setmethods__["dU1"] = _fmcore.TFmMotorInputObject_dU1_set
    __swig_getmethods__["dU1"] = _fmcore.TFmMotorInputObject_dU1_get
    if _newclass:dU1 = _swig_property(_fmcore.TFmMotorInputObject_dU1_get, _fmcore.TFmMotorInputObject_dU1_set)
    __swig_setmethods__["dU2"] = _fmcore.TFmMotorInputObject_dU2_set
    __swig_getmethods__["dU2"] = _fmcore.TFmMotorInputObject_dU2_get
    if _newclass:dU2 = _swig_property(_fmcore.TFmMotorInputObject_dU2_get, _fmcore.TFmMotorInputObject_dU2_set)
    __swig_setmethods__["dU3"] = _fmcore.TFmMotorInputObject_dU3_set
    __swig_getmethods__["dU3"] = _fmcore.TFmMotorInputObject_dU3_get
    if _newclass:dU3 = _swig_property(_fmcore.TFmMotorInputObject_dU3_get, _fmcore.TFmMotorInputObject_dU3_set)
    __swig_setmethods__["dU4"] = _fmcore.TFmMotorInputObject_dU4_set
    __swig_getmethods__["dU4"] = _fmcore.TFmMotorInputObject_dU4_get
    if _newclass:dU4 = _swig_property(_fmcore.TFmMotorInputObject_dU4_get, _fmcore.TFmMotorInputObject_dU4_set)
    def __init__(self): 
        this = _fmcore.new_TFmMotorInputObject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmMotorInputObject
    __del__ = lambda self : None;
TFmMotorInputObject_swigregister = _fmcore.TFmMotorInputObject_swigregister
TFmMotorInputObject_swigregister(TFmMotorInputObject)


def fmMotorInputObject_serialize(*args):
  return _fmcore.fmMotorInputObject_serialize(*args)
fmMotorInputObject_serialize = _fmcore.fmMotorInputObject_serialize

def fmMotorInputObject_deserialize(*args):
  return _fmcore.fmMotorInputObject_deserialize(*args)
fmMotorInputObject_deserialize = _fmcore.fmMotorInputObject_deserialize

def fmMotorInputObject_tomessage(*args):
  return _fmcore.fmMotorInputObject_tomessage(*args)
fmMotorInputObject_tomessage = _fmcore.fmMotorInputObject_tomessage

def fmMotorInputObject_frommessage(*args):
  return _fmcore.fmMotorInputObject_frommessage(*args)
fmMotorInputObject_frommessage = _fmcore.fmMotorInputObject_frommessage
class TFmRotorObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmRotorObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmRotorObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dT"] = _fmcore.TFmRotorObject_dT_set
    __swig_getmethods__["dT"] = _fmcore.TFmRotorObject_dT_get
    if _newclass:dT = _swig_property(_fmcore.TFmRotorObject_dT_get, _fmcore.TFmRotorObject_dT_set)
    __swig_setmethods__["dW1"] = _fmcore.TFmRotorObject_dW1_set
    __swig_getmethods__["dW1"] = _fmcore.TFmRotorObject_dW1_get
    if _newclass:dW1 = _swig_property(_fmcore.TFmRotorObject_dW1_get, _fmcore.TFmRotorObject_dW1_set)
    __swig_setmethods__["dW2"] = _fmcore.TFmRotorObject_dW2_set
    __swig_getmethods__["dW2"] = _fmcore.TFmRotorObject_dW2_get
    if _newclass:dW2 = _swig_property(_fmcore.TFmRotorObject_dW2_get, _fmcore.TFmRotorObject_dW2_set)
    __swig_setmethods__["dW3"] = _fmcore.TFmRotorObject_dW3_set
    __swig_getmethods__["dW3"] = _fmcore.TFmRotorObject_dW3_get
    if _newclass:dW3 = _swig_property(_fmcore.TFmRotorObject_dW3_get, _fmcore.TFmRotorObject_dW3_set)
    __swig_setmethods__["dW4"] = _fmcore.TFmRotorObject_dW4_set
    __swig_getmethods__["dW4"] = _fmcore.TFmRotorObject_dW4_get
    if _newclass:dW4 = _swig_property(_fmcore.TFmRotorObject_dW4_get, _fmcore.TFmRotorObject_dW4_set)
    def __init__(self): 
        this = _fmcore.new_TFmRotorObject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmRotorObject
    __del__ = lambda self : None;
TFmRotorObject_swigregister = _fmcore.TFmRotorObject_swigregister
TFmRotorObject_swigregister(TFmRotorObject)


def fmRotorObject_serialize(*args):
  return _fmcore.fmRotorObject_serialize(*args)
fmRotorObject_serialize = _fmcore.fmRotorObject_serialize

def fmRotorObject_deserialize(*args):
  return _fmcore.fmRotorObject_deserialize(*args)
fmRotorObject_deserialize = _fmcore.fmRotorObject_deserialize

def fmRotorObject_tomessage(*args):
  return _fmcore.fmRotorObject_tomessage(*args)
fmRotorObject_tomessage = _fmcore.fmRotorObject_tomessage

def fmRotorObject_frommessage(*args):
  return _fmcore.fmRotorObject_frommessage(*args)
fmRotorObject_frommessage = _fmcore.fmRotorObject_frommessage
class TFmStatusObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmStatusObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmStatusObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["iType"] = _fmcore.TFmStatusObject_iType_set
    __swig_getmethods__["iType"] = _fmcore.TFmStatusObject_iType_get
    if _newclass:iType = _swig_property(_fmcore.TFmStatusObject_iType_get, _fmcore.TFmStatusObject_iType_set)
    __swig_setmethods__["iStatus"] = _fmcore.TFmStatusObject_iStatus_set
    __swig_getmethods__["iStatus"] = _fmcore.TFmStatusObject_iStatus_get
    if _newclass:iStatus = _swig_property(_fmcore.TFmStatusObject_iStatus_get, _fmcore.TFmStatusObject_iStatus_set)
    __swig_setmethods__["iStatus2"] = _fmcore.TFmStatusObject_iStatus2_set
    __swig_getmethods__["iStatus2"] = _fmcore.TFmStatusObject_iStatus2_get
    if _newclass:iStatus2 = _swig_property(_fmcore.TFmStatusObject_iStatus2_get, _fmcore.TFmStatusObject_iStatus2_set)
    def __init__(self): 
        this = _fmcore.new_TFmStatusObject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmStatusObject
    __del__ = lambda self : None;
TFmStatusObject_swigregister = _fmcore.TFmStatusObject_swigregister
TFmStatusObject_swigregister(TFmStatusObject)


def fmStatusObject_serialize(*args):
  return _fmcore.fmStatusObject_serialize(*args)
fmStatusObject_serialize = _fmcore.fmStatusObject_serialize

def fmStatusObject_deserialize(*args):
  return _fmcore.fmStatusObject_deserialize(*args)
fmStatusObject_deserialize = _fmcore.fmStatusObject_deserialize

def fmStatusObject_tomessage(*args):
  return _fmcore.fmStatusObject_tomessage(*args)
fmStatusObject_tomessage = _fmcore.fmStatusObject_tomessage

def fmStatusObject_frommessage(*args):
  return _fmcore.fmStatusObject_frommessage(*args)
fmStatusObject_frommessage = _fmcore.fmStatusObject_frommessage
class TFmInnerloopObject(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TFmInnerloopObject, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TFmInnerloopObject, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dRoll"] = _fmcore.TFmInnerloopObject_dRoll_set
    __swig_getmethods__["dRoll"] = _fmcore.TFmInnerloopObject_dRoll_get
    if _newclass:dRoll = _swig_property(_fmcore.TFmInnerloopObject_dRoll_get, _fmcore.TFmInnerloopObject_dRoll_set)
    __swig_setmethods__["dPitch"] = _fmcore.TFmInnerloopObject_dPitch_set
    __swig_getmethods__["dPitch"] = _fmcore.TFmInnerloopObject_dPitch_get
    if _newclass:dPitch = _swig_property(_fmcore.TFmInnerloopObject_dPitch_get, _fmcore.TFmInnerloopObject_dPitch_set)
    __swig_setmethods__["dYaw"] = _fmcore.TFmInnerloopObject_dYaw_set
    __swig_getmethods__["dYaw"] = _fmcore.TFmInnerloopObject_dYaw_get
    if _newclass:dYaw = _swig_property(_fmcore.TFmInnerloopObject_dYaw_get, _fmcore.TFmInnerloopObject_dYaw_set)
    __swig_setmethods__["dThrust"] = _fmcore.TFmInnerloopObject_dThrust_set
    __swig_getmethods__["dThrust"] = _fmcore.TFmInnerloopObject_dThrust_get
    if _newclass:dThrust = _swig_property(_fmcore.TFmInnerloopObject_dThrust_get, _fmcore.TFmInnerloopObject_dThrust_set)
    def __init__(self): 
        this = _fmcore.new_TFmInnerloopObject()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fmcore.delete_TFmInnerloopObject
    __del__ = lambda self : None;
TFmInnerloopObject_swigregister = _fmcore.TFmInnerloopObject_swigregister
TFmInnerloopObject_swigregister(TFmInnerloopObject)


def fmInnerloopObject_serialize(*args):
  return _fmcore.fmInnerloopObject_serialize(*args)
fmInnerloopObject_serialize = _fmcore.fmInnerloopObject_serialize

def fmInnerloopObject_deserialize(*args):
  return _fmcore.fmInnerloopObject_deserialize(*args)
fmInnerloopObject_deserialize = _fmcore.fmInnerloopObject_deserialize

def fmInnerloopObject_tomessage(*args):
  return _fmcore.fmInnerloopObject_tomessage(*args)
fmInnerloopObject_tomessage = _fmcore.fmInnerloopObject_tomessage

def fmInnerloopObject_frommessage(*args):
  return _fmcore.fmInnerloopObject_frommessage(*args)
fmInnerloopObject_frommessage = _fmcore.fmInnerloopObject_frommessage
# This file is compatible with both classic and new-style classes.


